import { Injectable, Logger } from '@nestjs/common'
import { IAiProvider } from './ai.provider.interface.js'
import { GoogleGenerativeAI } from '@google/generative-ai'
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { AppException } from '../../exception/app-exception.js'
import { ErrorCode } from '../../exception/error-code.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

@Injectable()
export class GeminiProvider implements IAiProvider {
	private readonly logger = new Logger(GeminiProvider.name)
	private readonly apiKeys: string[] = []
	private currentKeyIndex = 0
	private readonly keyCooldowns = new Map<number, number>()
	private readonly keyFailureCounts = new Map<number, number>()
	private promptConfig: any

	constructor() {
		// Load keys from API_KEY_GEMINIS (comma separated)
		const envKeys = process.env.API_KEY_GEMINIS
		if (envKeys) {
			this.apiKeys = envKeys
				.split(',')
				.map((k) => k.trim())
				.filter((k) => k.length > 0)
		}
		if (this.apiKeys.length === 0) {
			this.logger.warn('No Gemini API keys found in API_KEY_GEMINIS.')
		} else {
			this.logger.log(`Loaded ${this.apiKeys.length} Gemini API keys for Round-Robin.`)
		}

		// Load prompt config
		const configPath = path.join(__dirname, '../config/ai-prompt.json')
		try {
			const configRaw = fs.readFileSync(configPath, 'utf8')
			this.promptConfig = JSON.parse(configRaw)
		} catch (e) {
			this.logger.error('Failed to load ai-prompt.json', e)
			this.promptConfig = {
				systemInstruction: '',
				prompt: 'Extract bio from text.',
				formatRequirements: '',
			}
		}
	}

	private getNextAvailableKeyIndex(triedIndexes: Set<number>): number | null {
		const now = Date.now()
		for (let attempt = 0; attempt < this.apiKeys.length; attempt++) {
			const index = this.currentKeyIndex
			this.currentKeyIndex = (this.currentKeyIndex + 1) % this.apiKeys.length

			if (triedIndexes.has(index)) continue
			const cooldownUntil = this.keyCooldowns.get(index) || 0
			if (cooldownUntil > now) continue
			return index
		}
		return null
	}

	private classifyGeminiError(error: any): { reason: string; retryWithNextKey: boolean; cooldownMs: number } {
		const message = String(error?.message || error?.error?.message || error || '').toLowerCase()
		const status = Number(error?.status || error?.response?.status || message.match(/\b(4\d\d|5\d\d)\b/)?.[1] || 0)

		if (
			status === 401 ||
			status === 403 ||
			message.includes('api key not valid') ||
			message.includes('invalid api key') ||
			message.includes('permission denied')
		) {
			return { reason: 'invalid_or_unauthorized_key', retryWithNextKey: true, cooldownMs: 60 * 60 * 1000 }
		}

		if (
			status === 429 ||
			message.includes('quota') ||
			message.includes('rate limit') ||
			message.includes('resource_exhausted')
		) {
			return { reason: 'quota_or_rate_limited', retryWithNextKey: true, cooldownMs: 5 * 60 * 1000 }
		}

		if (
			status === 500 ||
			status === 502 ||
			status === 503 ||
			status === 504 ||
			message.includes('timeout') ||
			message.includes('econnreset') ||
			message.includes('fetch failed')
		) {
			return { reason: 'transient_provider_error', retryWithNextKey: true, cooldownMs: 30 * 1000 }
		}

		if (status >= 400 && status < 500) {
			return { reason: 'non_retryable_request_error', retryWithNextKey: false, cooldownMs: 0 }
		}

		return { reason: 'unknown_provider_error', retryWithNextKey: true, cooldownMs: 30 * 1000 }
	}

	private markKeyFailure(index: number, cooldownMs: number) {
		this.keyFailureCounts.set(index, (this.keyFailureCounts.get(index) || 0) + 1)
		if (cooldownMs > 0) {
			this.keyCooldowns.set(index, Date.now() + cooldownMs)
		}
	}

	private markKeySuccess(index: number) {
		this.keyFailureCounts.delete(index)
		this.keyCooldowns.delete(index)
	}

	async generateBio(inputText: string): Promise<string> {
		if (this.apiKeys.length === 0) {
			return `# Mock Bio generated by GeminiProvider\n\nNo API key provided.\n\nSource: ${inputText}`
		}

		const fullPrompt = inputText
		const triedIndexes = new Set<number>()
		const errors: Array<{ keySuffix: string; reason: string }> = []

		while (triedIndexes.size < this.apiKeys.length) {
			const keyIndex = this.getNextAvailableKeyIndex(triedIndexes)
			if (keyIndex === null) break

			triedIndexes.add(keyIndex)
			const key = this.apiKeys[keyIndex]
			const genAI = new GoogleGenerativeAI(key)
			const model = genAI.getGenerativeModel({
				model: 'gemini-flash-latest',
				systemInstruction: this.promptConfig.systemInstruction,
			})

			try {
				const result = await model.generateContent(fullPrompt)
				this.markKeySuccess(keyIndex)
				return result.response.text()
			} catch (error) {
				const classification = this.classifyGeminiError(error)
				this.markKeyFailure(keyIndex, classification.cooldownMs)
				errors.push({ keySuffix: key.slice(-4), reason: classification.reason })
				this.logger.warn(
					`Gemini generation failed using key ending in ...${key.slice(-4)} (${classification.reason}).`,
					error,
				)

				if (!classification.retryWithNextKey) {
					throw new AppException(ErrorCode.InternalServerError, { reason: 'ai_generation_failed' })
				}
			}
		}

		this.logger.error('All available Gemini API keys failed or are cooling down.', errors)
		throw new AppException(ErrorCode.InternalServerError, {
			reason: 'all_gemini_keys_failed',
			attempts: errors,
		})
	}
}

