import { Injectable, Logger } from '@nestjs/common'
import { IAiProvider } from './ai.provider.interface.js'
import { GoogleGenerativeAI } from '@google/generative-ai'
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { AppException } from '../../exception/app-exception.js'
import { ErrorCode } from '../../exception/error-code.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

@Injectable()
export class GeminiProvider implements IAiProvider {
	private readonly logger = new Logger(GeminiProvider.name)
	private readonly apiKeys: string[] = []
	private currentKeyIndex = 0
	private promptConfig: any

	constructor() {
		// Load keys from API_KEY_GEMINIS (comma separated)
		const envKeys = process.env.API_KEY_GEMINIS
		if (envKeys) {
			this.apiKeys = envKeys
				.split(',')
				.map((k) => k.trim())
				.filter((k) => k.length > 0)
		}
		if (this.apiKeys.length === 0) {
			this.logger.warn('No Gemini API keys found in API_KEY_GEMINIS.')
		} else {
			this.logger.log(`Loaded ${this.apiKeys.length} Gemini API keys for Round-Robin.`)
		}

		// Load prompt config
		const configPath = path.join(__dirname, '../config/ai-prompt.json')
		try {
			const configRaw = fs.readFileSync(configPath, 'utf8')
			this.promptConfig = JSON.parse(configRaw)
		} catch (e) {
			this.logger.error('Failed to load ai-prompt.json', e)
			this.promptConfig = {
				systemInstruction: '',
				prompt: 'Extract bio from text.',
				formatRequirements: '',
			}
		}
	}

	private getNextKey(): string {
		if (this.apiKeys.length === 0) {
			throw new AppException(ErrorCode.InternalServerError, { reason: 'gemini_keys_missing' })
		}
		const key = this.apiKeys[this.currentKeyIndex]
		this.currentKeyIndex = (this.currentKeyIndex + 1) % this.apiKeys.length
		return key
	}

	async generateBio(inputText: string): Promise<string> {
		if (this.apiKeys.length === 0) {
			return `# Mock Bio generated by GeminiProvider\n\nNo API key provided.\n\nSource: ${inputText}`
		}

		const key = this.getNextKey()
		const genAI = new GoogleGenerativeAI(key)
		const model = genAI.getGenerativeModel({
			model: 'gemini-flash-latest',
			systemInstruction: this.promptConfig.systemInstruction,
		})

		const fullPrompt = inputText

		try {
			const result = await model.generateContent(fullPrompt)
			return result.response.text()
		} catch (error) {
			this.logger.error(`Gemini generation failed using key ending in ...${key.slice(-4)}`, error)
			throw new AppException(ErrorCode.InternalServerError, { reason: 'ai_generation_failed' })
		}
	}
}

