services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass MySecurePassword123 --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "MySecurePassword123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local